// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agfaipsrevtdslvpkfnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnZmFpcHNyZXZ0ZHNsdnBrZm5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDk3MjMsImV4cCI6MjA2NjE4NTcyM30.AnUb4Y2bvTgvuOc5hm4S78eJbW0C1kddwji3kQP_4Ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);